### ISSUE TITLE
Named export 'all' not found. The requested module 'deepmerge' is a CommonJS module

### ISSUE THREAD

**Issue by rankun203** [datalogix/google-fonts-helper#29]
Failed to compile in a Next.js project using TypeScript.

```bash
import { all } from 'deepmerge';
         ^^^
SyntaxError: Named export 'all' not found. The requested module 'deepmerge' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'deepmerge';
const { all } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at Loader.import (internal/modules/esm/loader.js:178:24)
```

**Comment by rankun203** [comment]
Found a similar issue in Webpack, for the exact same package `deepmerge`: https://github.com/webpack/webpack/issues/5756

**Comment by rankun203** [comment]
I've removed the `mjs` from `google-fonts-helper` to make it work for now, will need to find another way to fix it though.

```bash
pnpm add git+ssh://git@github.com:rankun203/google-fonts-helper#v3.0.0-cjs
```

It's only a temporary solution.

**Comment by boomermath** [comment]
I've had this same problem too, using [Astro](https://astro.build) beta

**Comment by cimchd** [comment]
Same probleme here in a vite project with es-modules (type: 'module' in package.json). Besides deepmerge the same problem occured also for fs-extra which also does not provide valid named esm exports.

To provide valid esm export you could easily change both imports in index.mjs like proposed in the error message: 

```js 
import deepmergeImport from 'deepmerge';
const { all } = deepmergeImport ;

import fsExtraImport from 'fs-extra';
const { pathExistsSync, outputFile } = fsExtraImport ;
```
I can provide the PR if needed.
