### ISSUE TITLE
Add support variable fonts

### ISSUE THREAD

**Issue by jiblett1000** [datalogix/google-fonts-helper#42]
Hey there. Just wondering if you're planning to add variable font support to the url constructor? I could take a stab at a PR, but I'm not terribly familiar with the code yet.

**Comment by ricardogobbosouza** [comment]
Hi @jiblett1000 
Could you better describe what `Variable fonts` would be about?

**Comment by jiblett1000** [comment]
@ricardogobbosouza Definitely! So this is the Google fonts API info on variable fonts in the v2 API. 

https://developers.google.com/fonts/docs/css2

You can use a sort of spread type syntax to define a font range and return a "variable font". Something like `200..800` instead of different weights separated by a semicolon as it is now (400;600;700). 

Here's some general info on variable fonts as well.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide

Depending on the number of weights you're using in a project, using a variable font instead of multiple separate font files (weights, styles, etc) can potentially end up being a smaller file size and more flexible.

**Comment by ricardogobbosouza** [comment]
I hadn't seen that...will work on that soon

Thanks

**Comment by jiblett1000** [comment]
@ricardogobbosouza Awesome! Very much appreciated. I think it will be a great addition ☺️
